/sim:
  ros__parameters:
    waypoint_mode: "OPPOSITE_EDGES"
    anchor_strategy: "FIXED"
    interpolation_method: "linear"
    namespace: "drone_sim"
    dt: 0.1
    drone_speed: 3.0
    num_waypoints: 7
    wait_time: 2.0
    bounds: [10.0, 10.0, 10.0]
